from django.urls import path
from HospitalManagement.views import *

urlpatterns =[
    path('', home ,  name='home'),
    path('login/', Login , name="Login"),
    path('logout/', logout_admin , name="logout_admin"),
    path('base/', admin_dashboard , name="admin_dashboard"),
    path('adminp', admin_patient , name="admin_patient"),
    path('admind', admin_doctor , name="admin_doctor"),
    path('admina', admin_appointment , name="admin_appointment"),
    path('admindv', admin_view_doctor , name="admin_view_doctor"),
    path('adminda', admin_add_doctor , name="admin_add_doctor"),
    path('adminad', admin_approve_doctor , name="admin_approve_doctor"),
    path('adminap', admin_approve_patient , name="admin_approve_patient"),
    path('adminaa', admin_approve_appointment , name="admin_approve_appointment"),
    path('approve_doctor/<int:pk>', approve_doctor , name="approve_doctor"),
    path('reject_doctor/<int:pk>', reject_doctor , name="reject_doctor"),
    path('approve_patient/<int:pk>', approve_patient , name="approve_patient"),
    path('reject_patient/<int:pk>', reject_patient , name="reject_patient"),
    path('approve_appointment/<int:pk>', approve_appointment , name="approve_appointment"),
    path('reject_appointment/<int:pk>', reject_appointment , name="reject_appointment"),
    path('adminav/', admin_view_appointment , name="admin_view_appointment"),
    path('adminbook/', admin_book_appointment , name="admin_book_appointment"),
    path('adminvp/', admin_view_patient , name="admin_view_patient"),
    path('adminsp/', doctor_specialization , name="doctor_specialization"),
    path('adminam/', admit_patient , name="admit_patient"),
    path('base2/', patient_dashboard , name="patient_dashboard"),
    path('patientsignup/', patientsignup , name="patientsignup"),
    path('patientlogin/', patientlogin, name="patientlogin"),
    path('doctorsignup/', doctorsignup , name="doctorsignup"),
    path('doctorlogin/', doctorlogin, name="doctorlogin"),
    path('doctor_patient/', doctor_patient, name="doctor_patient"),
    path('doctor_appointment/', doctor_appointment, name="doctor_appointment"),
    path('doctor_dashboard/', doctor_dashboard_view, name="doctor_dashboard"),
    path('doctor_dashboard/', doctor_dashboard, name="doctor_dashboard"),
    path('patient_dashboard/', patient_dashboard_view, name="patient_dashboard"),
    path('patient_appointment/', patient_appointment, name="patient_appointment"),
    path('patient_view_appointment/', patient_view_appointment, name="patient_view_appointment"),
    path('patient_book_appointment/', patient_book_appointment, name="patient_book_appointment"),
    path('doctor_view_patient/', doctor_view_patient, name="doctor_view_patient"),
    path('admin_update/<int:pk>',admin_update,name="admin_update"),
    path('admin_delete/<int:pk>',admin_delete,name="admin_delete"),
    path('admin_update_d/<int:pk>',admin_update_d,name="admin_update_d"),
    path('admin_delete_d/<int:pk>',admin_delete_d,name="admin_delete_d"),
    path('doctor_add/',doctor_add,name="doctor_add"),

    
]
