# Generated by Django 4.2.5 on 2023-09-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0002_alter_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='profile'),
        ),
    ]
